// import
@Library("stulib@master")
import org.stubrown.pipelines.simplescripted.*
// instantiate
pl = new simple()
// work
pl.build(qa)
pl.deploy(qa,api)
pl.test(regression)
pl.deploy(staging,api)
pl.test(load)
pl.deploy(prod,api)


scripted/simplescripted/Jenkinsfile
scripted/simplescripted/Jenkinsfile