// import
@Library("jenkins-shared-libraries@release")
import org.stubrown.pipelines.simplescripted.*
// instantiate
pl = new simple()
// work
pl.build()
pl.deploy(qa,api)
pl.test(regression)
pl.deploy(staging,api)
pl.test(load)
pl.deploy(prod,api)