@Library("jenkins-shared-library") _

log.info "Starting : ${env.JOB_NAME}"
def stu = ${env.JOB_NAME}

standardPipeline{
    projectName = "123"
    serverDomain = "Project 1 server domain"

}

log.warning 'Nothing to do!'